services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - 80:80
    volumes:
      - web_data:/var/www/html

  jenkins:
    image: custom-jenkins
    user: root
    ports:
      - 8080:8080
      - 8081:8081
      - 8091:8091
      - 8090:8090
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  web_data:
  jenkins_data:
